### ISSUE TITLE
Switch from Mandrill to Mailgun

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/mail-fac#4]
We are currently using Mandrill, but see http://blog.mandrill.com/important-changes-to-mandrill.html, so we probably need to update to use Mailgun instead.

**Comment by yepher** [comment]
Just incase it can help here is the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this [Slack channel](http://slack.sparkpost.com) is available if you need help with the migration.

You get 100,000 free emails per month.

**Comment by iteles** [comment]
We could also take https://github.com/dwyl/sendemail for a spin if we wanted to contribute to something open source (based on Amazon SES).

**Comment by sofer** [comment]
@iteles @izaakrogan @oturnermajor fix successfully deployed and tested.

**Comment by sofer** [comment]
btw love the look of https://github.com/dwyl/sendemail

**Comment by iteles** [comment]
@sofer We're using it for OA, but would be get some more use cases to expand on it!
